

export const country = [
  { name: "South Georgia", flag: "https://flagcdn.com/w320/gs.png", code: "en" },
  { name: "Grenada", flag: "https://flagcdn.com/w320/gd.png", code: "en" },
  { name: "Switzerland", flag: "https://flagcdn.com/w320/ch.png", code: "de" }, // German là ngôn ngữ chính
  { name: "Sierra Leone", flag: "https://flagcdn.com/w320/sl.png", code: "en" },
  { name: "Hungary", flag: "https://flagcdn.com/w320/hu.png", code: "hu" },
  { name: "Taiwan", flag: "https://flagcdn.com/w320/tw.png", code: "zh" }, // Chinese (Traditional)
  { name: "Wallis and Futuna", flag: "https://flagcdn.com/w320/wf.png", code: "fr" },
  { name: "Barbados", flag: "https://flagcdn.com/w320/bb.png", code: "en" },
  { name: "Pitcairn Islands", flag: "https://flagcdn.com/w320/pn.png", code: "en" },
  { name: "Ivory Coast", flag: "https://flagcdn.com/w320/ci.png", code: "fr" },
  { name: "Tunisia", flag: "https://flagcdn.com/w320/tn.png", code: "ar" },
  { name: "Italy", flag: "https://flagcdn.com/w320/it.png", code: "it" },
  { name: "Benin", flag: "https://flagcdn.com/w320/bj.png", code: "fr" },
  { name: "Indonesia", flag: "https://flagcdn.com/w320/id.png", code: "id" },
  { name: "Cape Verde", flag: "https://flagcdn.com/w320/cv.png", code: "pt" },
  { name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w320/kn.png", code: "en" },
  { name: "Laos", flag: "https://flagcdn.com/w320/la.png", code: "lo" },
  { name: "Caribbean Netherlands", flag: "https://flagcdn.com/w320/bq.png", code: "nl" },
  { name: "Uganda", flag: "https://flagcdn.com/w320/ug.png", code: "en" },
  { name: "Andorra", flag: "https://flagcdn.com/w320/ad.png", code: "ca" }, // Catalan
  { name: "Burundi", flag: "https://flagcdn.com/w320/bi.png", code: "fr" },
  {
    name: "South Africa",
    flag: "https://flagcdn.com/w320/za.png", code: "en"
  },
  { name: "France", flag: "https://flagcdn.com/w320/fr.png", code: "fr" },
  { name: "Libya", flag: "https://flagcdn.com/w320/ly.png", code: "ar" },
  { name: "Mexico", flag: "https://flagcdn.com/w320/mx.png", code: "es" },
  { name: "Gabon", flag: "https://flagcdn.com/w320/ga.png", code: "fr" },
  { name: "Northern Mariana Islands", flag: "https://flagcdn.com/w320/mp.png", code: "en" },
  { name: "North Macedonia", flag: "https://flagcdn.com/w320/mk.png", code: "mk" },
  { name: "China", flag: "https://flagcdn.com/w320/cn.png", code: "zh" }, // Chinese (Simplified)
  { name: "Yemen", flag: "https://flagcdn.com/w320/ye.png", code: "ar" },
  { name: "Saint Barthélemy", flag: "https://flagcdn.com/w320/bl.png", code: "fr" },
  { name: "Guernsey", flag: "https://flagcdn.com/w320/gg.png", code: "en" },
  { name: "Solomon Islands", flag: "https://flagcdn.com/w320/sb.png", code: "en" },
  { name: "Svalbard and Jan Mayen", flag: "https://flagcdn.com/w320/sj.png", code: "no" },
  { name: "Faroe Islands", flag: "https://flagcdn.com/w320/fo.png", code: "fo" },
  { name: "Uzbekistan", flag: "https://flagcdn.com/w320/uz.png", code: "uz" },
  { name: "Egypt", flag: "https://flagcdn.com/w320/eg.png", code: "ar" },
  { name: "Senegal", flag: "https://flagcdn.com/w320/sn.png", code: "fr" },
  { name: "Sri Lanka", flag: "https://flagcdn.com/w320/lk.png", code: "si" }, // Sinhala
  { name: "Palestine", flag: "https://flagcdn.com/w320/ps.png", code: "ar" },
  { name: "Bangladesh", flag: "https://flagcdn.com/w320/bd.png", code: "bn" },
  { name: "Peru", flag: "https://flagcdn.com/w320/pe.png", code: "es" },
  { name: "Singapore", flag: "https://flagcdn.com/w320/sg.png", code: "en" },
  { name: "Turkey", flag: "https://flagcdn.com/w320/tr.png", code: "tr" },
  { name: "Afghanistan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png", code: "ps" }, // Pashto
  { name: "Aruba", flag: "https://flagcdn.com/w320/aw.png", code: "nl" },
  { name: "Cook Islands", flag: "https://flagcdn.com/w320/ck.png", code: "en" },
  { name: "United Kingdom", flag: "https://flagcdn.com/w320/gb.png", code: "en" },
  { name: "Zambia", flag: "https://flagcdn.com/w320/zm.png", code: "en" },
  { name: "Finland", flag: "https://flagcdn.com/w320/fi.png", code: "fi" },
  { name: "Niger", flag: "https://flagcdn.com/w320/ne.png", code: "fr" },
  { name: "Christmas Island", flag: "https://flagcdn.com/w320/cx.png", code: "en" },
  { name: "Tokelau", flag: "https://flagcdn.com/w320/tk.png", code: "en" },
  { name: "Guinea-Bissau", flag: "https://flagcdn.com/w320/gw.png", code: "pt" },
  { name: "Azerbaijan", flag: "https://flagcdn.com/w320/az.png", code: "az" },
  { name: "Réunion", flag: "https://flagcdn.com/w320/re.png", code: "fr" },
  { name: "Djibouti", flag: "https://flagcdn.com/w320/dj.png", code: "fr" },
  { name: "North Korea", flag: "https://flagcdn.com/w320/kp.png", code: "ko" },
  { name: "Mauritius", flag: "https://flagcdn.com/w320/mu.png", code: "en" },
  { name: "Montserrat", flag: "https://flagcdn.com/w320/ms.png", code: "en" },
  { name: "United States Virgin Islands", flag: "https://flagcdn.com/w320/vi.png", code: "en" },
  { name: "Colombia", flag: "https://flagcdn.com/w320/co.png", code: "es" },
  { name: "Greece", flag: "https://flagcdn.com/w320/gr.png", code: "el" },
  { name: "Croatia", flag: "https://flagcdn.com/w320/hr.png", code: "hr" },
  { name: "Morocco", flag: "https://flagcdn.com/w320/ma.png", code: "ar" },
  { name: "Algeria", flag: "https://flagcdn.com/w320/dz.png", code: "ar" },
  { name: "Antarctica", flag: "https://flagcdn.com/w320/aq.png", code: "en" },
  { name: "Netherlands", flag: "https://flagcdn.com/w320/nl.png", code: "nl" },
  { name: "Sudan", flag: "https://flagcdn.com/w320/sd.png", code: "ar" },
  { name: "Fiji", flag: "https://flagcdn.com/w320/fj.png", code: "en" },
  { name: "Liechtenstein", flag: "https://flagcdn.com/w320/li.png", code: "de" },
  { name: "Nepal", flag: "https://flagcdn.com/w320/np.png", code: "ne" },
  { name: "Puerto Rico", flag: "https://flagcdn.com/w320/pr.png", code: "es" },
  { name: "Georgia", flag: "https://flagcdn.com/w320/ge.png", code: "ka" },
  { name: "Pakistan", flag: "https://flagcdn.com/w320/pk.png", code: "ur" }, // Urdu
  { name: "Monaco", flag: "https://flagcdn.com/w320/mc.png", code: "fr" },
  { name: "Botswana", flag: "https://flagcdn.com/w320/bw.png", code: "en" },
  { name: "Lebanon", flag: "https://flagcdn.com/w320/lb.png", code: "ar" },
  { name: "Papua New Guinea", flag: "https://flagcdn.com/w320/pg.png", code: "en" },
  { name: "Mayotte", flag: "https://flagcdn.com/w320/yt.png", code: "fr" },
  { name: "Dominican Republic", flag: "https://flagcdn.com/w320/do.png", code: "es" },
  { name: "Norfolk Island", flag: "https://flagcdn.com/w320/nf.png", code: "en" },
  { name: "Bouvet Island", flag: "https://flagcdn.com/w320/bv.png", code: "no" },
  { name: "Qatar", flag: "https://flagcdn.com/w320/qa.png", code: "ar" },
  { name: "Madagascar", flag: "https://flagcdn.com/w320/mg.png", code: "mg" }, // Malagasy
  { name: "India", flag: "https://flagcdn.com/w320/in.png", code: "hi" }, // Hindi
  { name: "Syria", flag: "https://flagcdn.com/w320/sy.png", code: "ar" },
  { name: "Montenegro", flag: "https://flagcdn.com/w320/me.png", code: "sr" }, // Serbian
  { name: "Eswatini", flag: "https://flagcdn.com/w320/sz.png", code: "en" },
  { name: "Paraguay", flag: "https://flagcdn.com/w320/py.png", code: "es" },
  { name: "El Salvador", flag: "https://flagcdn.com/w320/sv.png", code: "es" },
  { name: "Ukraine", flag: "https://flagcdn.com/w320/ua.png", code: "uk" },
  { name: "Isle of Man", flag: "https://flagcdn.com/w320/im.png", code: "en" },
  { name: "Namibia", flag: "https://flagcdn.com/w320/na.png", code: "en" },
  { name: "United Arab Emirates", flag: "https://flagcdn.com/w320/ae.png", code: "ar" },
  { name: "Bulgaria", flag: "https://flagcdn.com/w320/bg.png", code: "bg" },
  { name: "Greenland", flag: "https://flagcdn.com/w320/gl.png", code: "kl" }, // Kalaallisut
  { name: "Germany", flag: "https://flagcdn.com/w320/de.png", code: "de" },
  { name: "Cambodia", flag: "https://flagcdn.com/w320/kh.png", code: "km" },
  { name: "Iraq", flag: "https://flagcdn.com/w320/iq.png", code: "ar" },
  { name: "French Southern and Antarctic Lands", flag: "https://flagcdn.com/w320/tf.png", code: "fr" },
  { name: "Sweden", flag: "https://flagcdn.com/w320/se.png", code: "sv" },
  { name: "Cuba", flag: "https://flagcdn.com/w320/cu.png", code: "es" },
  { name: "Kyrgyzstan", flag: "https://flagcdn.com/w320/kg.png", code: "ky" },
  { name: "Russia", flag: "https://flagcdn.com/w320/ru.png", code: "ru" },
  { name: "Malaysia", flag: "https://flagcdn.com/w320/my.png", code: "ms" },
  { name: "São Tomé and Príncipe", flag: "https://flagcdn.com/w320/st.png", code: "pt" },
  { name: "Cyprus", flag: "https://flagcdn.com/w320/cy.png", code: "el" },
  { name: "Canada", flag: "https://flagcdn.com/w320/ca.png", code: "en" },
  { name: "Malawi", flag: "https://flagcdn.com/w320/mw.png", code: "en" },
  { name: "Saudi Arabia", flag: "https://flagcdn.com/w320/sa.png", code: "ar" },
  { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w320/ba.png", code: "bs" }, // Bosnian
  { name: "Ethiopia", flag: "https://flagcdn.com/w320/et.png", code: "am" }, // Amharic
  { name: "Spain", flag: "https://flagcdn.com/w320/es.png", code: "es" },
  { name: "Slovenia", flag: "https://flagcdn.com/w320/si.png", code: "sl" },
  { name: "Oman", flag: "https://flagcdn.com/w320/om.png", code: "ar" },
  { name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/w320/pm.png", code: "fr" },
  { name: "Macau", flag: "https://flagcdn.com/w320/mo.png", code: "zh" },
  { name: "San Marino", flag: "https://flagcdn.com/w320/sm.png", code: "it" },
  { name: "Lesotho", flag: "https://flagcdn.com/w320/ls.png", code: "en" },
  { name: "Marshall Islands", flag: "https://flagcdn.com/w320/mh.png", code: "en" },
  { name: "Sint Maarten", flag: "https://flagcdn.com/w320/sx.png", code: "nl" },
  { name: "Iceland", flag: "https://flagcdn.com/w320/is.png", code: "is" },
  { name: "Luxembourg", flag: "https://flagcdn.com/w320/lu.png", code: "lb" }, // Luxembourgish
  { name: "Argentina", flag: "https://flagcdn.com/w320/ar.png", code: "es" },
  { name: "Turks and Caicos Islands", flag: "https://flagcdn.com/w320/tc.png", code: "en" },
  { name: "Nauru", flag: "https://flagcdn.com/w320/nr.png", code: "en" },
  { name: "Cocos (Keeling) Islands", flag: "https://flagcdn.com/w320/cc.png", code: "en" },
  { name: "Western Sahara", flag: "https://flagcdn.com/w320/eh.png", code: "ar" },
  { name: "Dominica", flag: "https://flagcdn.com/w320/dm.png", code: "en" },
  { name: "Costa Rica", flag: "https://flagcdn.com/w320/cr.png", code: "es" },
  { name: "Australia", flag: "https://flagcdn.com/w320/au.png", code: "en" },
  { name: "Thailand", flag: "https://flagcdn.com/w320/th.png", code: "th" },
  { name: "Haiti", flag: "https://flagcdn.com/w320/ht.png", code: "fr" },
  { name: "Tuvalu", flag: "https://flagcdn.com/w320/tv.png", code: "en" },
  { name: "Honduras", flag: "https://flagcdn.com/w320/hn.png", code: "es" },
  { name: "Equatorial Guinea", flag: "https://flagcdn.com/w320/gq.png", code: "es" },
  { name: "Saint Lucia", flag: "https://flagcdn.com/w320/lc.png", code: "en" },
  { name: "French Polynesia", flag: "https://flagcdn.com/w320/pf.png", code: "fr" },
  { name: "Belarus", flag: "https://flagcdn.com/w320/by.png", code: "be" },
  { name: "Latvia", flag: "https://flagcdn.com/w320/lv.png", code: "lv" },
  { name: "Palau", flag: "https://flagcdn.com/w320/pw.png", code: "en" },
  { name: "Guadeloupe", flag: "https://flagcdn.com/w320/gp.png", code: "fr" },
  { name: "Philippines", flag: "https://flagcdn.com/w320/ph.png", code: "tl" }, // Tagalog
  { name: "Gibraltar", flag: "https://flagcdn.com/w320/gi.png", code: "en" },
  { name: "Denmark", flag: "https://flagcdn.com/w320/dk.png", code: "da" },
  { name: "Cameroon", flag: "https://flagcdn.com/w320/cm.png", code: "fr" },
  { name: "Guinea", flag: "https://flagcdn.com/w320/gn.png", code: "fr" },
  { name: "Bahrain", flag: "https://flagcdn.com/w320/bh.png", code: "ar" },
  { name: "Suriname", flag: "https://flagcdn.com/w320/sr.png", code: "nl" },
  { name: "DR Congo", flag: "https://flagcdn.com/w320/cd.png", code: "fr" },
  { name: "Somalia", flag: "https://flagcdn.com/w320/so.png", code: "so" },
  { name: "Czechia", flag: "https://flagcdn.com/w320/cz.png", code: "cs" },
  { name: "New Caledonia", flag: "https://flagcdn.com/w320/nc.png", code: "fr" },
  { name: "Vanuatu", flag: "https://flagcdn.com/w320/vu.png", code: "en" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", flag: "https://flagcdn.com/w320/sh.png", code: "en" },
  { name: "Togo", flag: "https://flagcdn.com/w320/tg.png", code: "fr" },
  { name: "British Virgin Islands", flag: "https://flagcdn.com/w320/vg.png", code: "en" },
  { name: "Kenya", flag: "https://flagcdn.com/w320/ke.png", code: "en" },
  { name: "Niue", flag: "https://flagcdn.com/w320/nu.png", code: "en" },
  { name: "Heard Island and McDonald Islands", flag: "https://flagcdn.com/w320/hm.png", code: "en" },
  { name: "Rwanda", flag: "https://flagcdn.com/w320/rw.png", code: "rw" }, // Kinyarwanda
  { name: "Estonia", flag: "https://flagcdn.com/w320/ee.png", code: "et" },
  { name: "Romania", flag: "https://flagcdn.com/w320/ro.png", code: "ro" },
  { name: "Trinidad and Tobago", flag: "https://flagcdn.com/w320/tt.png", code: "en" },
  { name: "Guyana", flag: "https://flagcdn.com/w320/gy.png", code: "en" },
  { name: "Timor-Leste", flag: "https://flagcdn.com/w320/tl.png", code: "pt" },
  { name: "Vietnamese", flag: "https://flagcdn.com/w320/vn.png", code: "vi" },
  { name: "Uruguay", flag: "https://flagcdn.com/w320/uy.png", code: "es" },
  { name: "Vatican City", flag: "https://flagcdn.com/w320/va.png", code: "it" },
  { name: "Hong Kong", flag: "https://flagcdn.com/w320/hk.png", code: "zh" },
  { name: "Austria", flag: "https://flagcdn.com/w320/at.png", code: "de" },
  { name: "Antigua and Barbuda", flag: "https://flagcdn.com/w320/ag.png", code: "en" },
  { name: "Turkmenistan", flag: "https://flagcdn.com/w320/tm.png", code: "tk" },
  { name: "Mozambique", flag: "https://flagcdn.com/w320/mz.png", code: "pt" },
  { name: "Panama", flag: "https://flagcdn.com/w320/pa.png", code: "es" },
  { name: "Micronesia", flag: "https://flagcdn.com/w320/fm.png", code: "en" },
  { name: "Ireland", flag: "https://flagcdn.com/w320/ie.png", code: "ga" }, // Irish
  { name: "Curaçao", flag: "https://flagcdn.com/w320/cw.png", code: "nl" },
  { name: "French Guiana", flag: "https://flagcdn.com/w320/gf.png", code: "fr" },
  { name: "Norway", flag: "https://flagcdn.com/w320/no.png", code: "no" },
  { name: "Åland Islands", flag: "https://flagcdn.com/w320/ax.png", code: "sv" },
  { name: "Central African Republic", flag: "https://flagcdn.com/w320/cf.png", code: "fr" },
  { name: "Burkina Faso", flag: "https://flagcdn.com/w320/bf.png", code: "fr" },
  { name: "Eritrea", flag: "https://flagcdn.com/w320/er.png", code: "ti" }, // Tigrinya
  { name: "Tanzania", flag: "https://flagcdn.com/w320/tz.png", code: "sw" }, // Swahili
  { name: "South Korea", flag: "https://flagcdn.com/w320/kr.png", code: "ko" },
  { name: "Jordan", flag: "https://flagcdn.com/w320/jo.png", code: "ar" },
  { name: "Mauritania", flag: "https://flagcdn.com/w320/mr.png", code: "ar" },
  { name: "Lithuania", flag: "https://flagcdn.com/w320/lt.png", code: "lt" },
  { name: "United States Minor Outlying Islands", flag: "https://flagcdn.com/w320/um.png", code: "en" },
  { name: "Slovakia", flag: "https://flagcdn.com/w320/sk.png", code: "sk" },
  { name: "Angola", flag: "https://flagcdn.com/w320/ao.png", code: "pt" },
  { name: "Kazakhstan", flag: "https://flagcdn.com/w320/kz.png", code: "kk" },
  { name: "Moldova", flag: "https://flagcdn.com/w320/md.png", code: "ro" },
  { name: "Mali", flag: "https://flagcdn.com/w320/ml.png", code: "fr" },
  { name: "Falkland Islands", flag: "https://flagcdn.com/w320/fk.png", code: "en" },
  { name: "Armenia", flag: "https://flagcdn.com/w320/am.png", code: "hy" },
  { name: "Samoa", flag: "https://flagcdn.com/w320/ws.png", code: "sm" },
  { name: "Jersey", flag: "https://flagcdn.com/w320/je.png", code: "en" },
  { name: "Japan", flag: "https://flagcdn.com/w320/jp.png", code: "ja" },
  { name: "Bolivia", flag: "https://flagcdn.com/w320/bo.png", code: "es" },
  { name: "Chile", flag: "https://flagcdn.com/w320/cl.png", code: "es" },
  { name: "English", flag: "https://flagcdn.com/w320/us.png", code: "en" },
  { name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w320/vc.png", code: "en" },
  { name: "Bermuda", flag: "https://flagcdn.com/w320/bm.png", code: "en" },
  { name: "Seychelles", flag: "https://flagcdn.com/w320/sc.png", code: "en" },
  { name: "British Indian Ocean Territory", flag: "https://flagcdn.com/w320/io.png", code: "en" },
  { name: "Guatemala", flag: "https://flagcdn.com/w320/gt.png", code: "es" },
  { name: "Ecuador", flag: "https://flagcdn.com/w320/ec.png", code: "es" },
  { name: "Martinique", flag: "https://flagcdn.com/w320/mq.png", code: "fr" },
  { name: "Tajikistan", flag: "https://flagcdn.com/w320/tj.png", code: "tg" },
  { name: "Malta", flag: "https://flagcdn.com/w320/mt.png", code: "mt" },
  { name: "Gambia", flag: "https://flagcdn.com/w320/gm.png", code: "en" },
  { name: "Nigeria", flag: "https://flagcdn.com/w320/ng.png", code: "en" },
  { name: "Bahamas", flag: "https://flagcdn.com/w320/bs.png", code: "en" },
  { name: "Kosovo", flag: "https://flagcdn.com/w320/xk.png", code: "sq" }, // Albanian
  { name: "Kuwait", flag: "https://flagcdn.com/w320/kw.png", code: "ar" },
  { name: "Maldives", flag: "https://flagcdn.com/w320/mv.png", code: "dv" }, // Dhivehi
  { name: "South Sudan", flag: "https://flagcdn.com/w320/ss.png", code: "en" },
  { name: "Iran", flag: "https://flagcdn.com/w320/ir.png", code: "fa" }, // Persian
  { name: "Albania", flag: "https://flagcdn.com/w320/al.png", code: "sq" },
  { name: "Brazil", flag: "https://flagcdn.com/w320/br.png", code: "pt" },
  { name: "Serbia", flag: "https://flagcdn.com/w320/rs.png", code: "sr" },
  { name: "Belize", flag: "https://flagcdn.com/w320/bz.png", code: "en" },
  { name: "Myanmar", flag: "https://flagcdn.com/w320/mm.png", code: "my" },
  { name: "Bhutan", flag: "https://flagcdn.com/w320/bt.png", code: "dz" }, // Dzongkha
  { name: "Venezuela", flag: "https://flagcdn.com/w320/ve.png", code: "es" },
  { name: "Liberia", flag: "https://flagcdn.com/w320/lr.png", code: "en" },
  { name: "Jamaica", flag: "https://flagcdn.com/w320/jm.png", code: "en" },
  { name: "Poland", flag: "https://flagcdn.com/w320/pl.png", code: "pl" },
  { name: "Cayman Islands", flag: "https://flagcdn.com/w320/ky.png", code: "en" },
  { name: "Brunei", flag: "https://flagcdn.com/w320/bn.png", code: "ms" },
  { name: "Comoros", flag: "https://flagcdn.com/w320/km.png", code: "fr" },
  { name: "Guam", flag: "https://flagcdn.com/w320/gu.png", code: "en" },
  { name: "Tonga", flag: "https://flagcdn.com/w320/to.png", code: "to" },
  { name: "Kiribati", flag: "https://flagcdn.com/w320/ki.png", code: "en" },
  { name: "Ghana", flag: "https://flagcdn.com/w320/gh.png", code: "en" },
  { name: "Chad", flag: "https://flagcdn.com/w320/td.png", code: "fr" },
  { name: "Zimbabwe", flag: "https://flagcdn.com/w320/zw.png", code: "en" },
  { name: "Saint Martin", flag: "https://flagcdn.com/w320/mf.png", code: "fr" },
  { name: "Mongolia", flag: "https://flagcdn.com/w320/mn.png", code: "mn" },
  { name: "Portugal", flag: "https://flagcdn.com/w320/pt.png", code: "pt" },
  { name: "American Samoa", flag: "https://flagcdn.com/w320/as.png", code: "en" },
  { name: "Republic of the Congo", flag: "https://flagcdn.com/w320/cg.png", code: "fr" },
  { name: "Belgium", flag: "https://flagcdn.com/w320/be.png", code: "nl" }, // Dutch
  { name: "Israel", flag: "https://flagcdn.com/w320/il.png", code: "he" },
  { name: "New Zealand", flag: "https://flagcdn.com/w320/nz.png", code: "en" },
  { name: "Nicaragua", flag: "https://flagcdn.com/w320/ni.png", code: "es" },
  { name: "Anguilla", flag: "https://flagcdn.com/w320/ai.png", code: "en" },
];